import {
  WEB_SOCKET_TYPES,
  WS_CHAT_ACTIONS,
  WS_CHAT_JOIN_MESSAGE,
  WS_CHAT_DELETE_MESSAGE,
  WS_CHAT_LEAVE_MESSAGE,
  WS_CHAT_SEND_MESSAGE,
} from "../../../../../packages/shared";

export type WsChatMessage =
  | WS_CHAT_JOIN_MESSAGE
  | WS_CHAT_DELETE_MESSAGE
  | WS_CHAT_LEAVE_MESSAGE
  | WS_CHAT_SEND_MESSAGE;
